### ISSUE TITLE
some errors in Building OLED 0.1

### ISSUE THREAD

**Issue by black111** [nkatzz/OLED#6]
when I build the project ,I found some errors,It seems some packages missing in /OLED/src/main/scala/oled/winnow/PlotTest2.scala "not found object scalatizk"

**Comment by black111** [comment]
The dependency of scalatizk should be added.

**Comment by nkatzz** [comment]
I know, sorry about that. If you remove PlotTest2.scala it should be ok.
I'll fix this asap. Are you trying to use the software? Do you need some
help?

**Comment by nkatzz** [comment]
I should be ok now.

**Comment by black111** [comment]
yeah,I'm trying to running this software

**Comment by black111** [comment]
I run this application according to the manual ,but the result is NaN and the file theory.lp only have  terminatedAt clauses.I'm sure the data is imported correctly.
tps: 0
fps: 0
fns: 0
precision: NaN
recall: NaN
f-score: NaN
training time: 164.038610865
theory size: 17

**Comment by nkatzz** [comment]
Yeah, sorry about that also, this is related to the order in which the data
are fetched from mongo. I fixed that. Easiest way to get it to work: Delete
everything, repeat the whole process as described on github. If you don't
want to do that:
1. drop caviar-train from your mongo
2. Download the data again, unzip and import caviar-train as described on
github
3. Delete oled-0.1.jar
4. Open app.runners.OLEDDefaultRunner and change line 55 from sortDbByField
= "None" to sortDbByField = "_id"
5. re-create the jar file and run it. Do:
sbt assembly
then copy the jar from target/scala-2.11/ to the root oled folder, run it
as specified on github.

If you don't want to touch the code (step 4) just do a pull. But you have
to do all other steps. That's why I'm saying that the easiest way is to
delete everything and repeat the whole process.

You should see the following theory in theory.lp:

terminatedAt(meeting(X0,X1),X2) :-
      happensAt(walking(X0),X2),
      happensAt(inactive(X1),X2).
terminatedAt(meeting(X0,X1),X2) :-
      happensAt(walking(X1),X2),
      happensAt(inactive(X0),X2).
terminatedAt(meeting(X0,X1),X2) :-
      happensAt(running(X1),X2),
      close(X1,X0,27,X2).
terminatedAt(meeting(X0,X1),X2) :-
      happensAt(running(X0),X2),
      close(X1,X0,27,X2).
terminatedAt(meeting(X0,X1),X2) :-
      happensAt(walking(X0),X2),
      close(X1,X0,27,X2),
      happensAt(walking(X1),X2).
initiatedAt(meeting(X0,X1),X2) :-
      close(X1,X0,27,X2),
      happensAt(active(X0),X2),
      happensAt(active(X1),X2).
initiatedAt(meeting(X0,X1),X2) :-
      close(X1,X0,27,X2),
      happensAt(inactive(X0),X2),
      happensAt(inactive(X1),X2).
initiatedAt(meeting(X0,X1),X2) :-
      close(X0,X1,40,X2),
      happensAt(active(X0),X2),
      happensAt(active(X1),X2),
      far(X0,X1,24,X2),
      close(X0,X1,34,X2).

You should get the following numbers after evaluating it on the test set:

tps: 882
fps: 198
fns: 100
precision: 0.81666666
recall: 0.898167
f-score: 0.8554801
training time:0.0
theory size: 0.0

Note that the stats printed on screen after training (NaNs etc) are not
important.

Tell me if everything is ok.

**Comment by black111** [comment]
It's very strange.I update the code and clone the code again,the results have no change.
Here is the theory in theory.pl:
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(walking(X0),X2),
      happensAt(inactive(X1),X2).
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(walking(X1),X2),
      happensAt(inactive(X0),X2).
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(running(X1),X2),
      close(X1,X0,27,X2).
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(running(X0),X2),
      close(X1,X0,27,X2).
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(walking(X0),X2),
      happensAt(walking(X1),X2).

**Comment by nkatzz** [comment]
That's very strange indeed. Did you drop caviar-train from mongo before
importing the new dataset? Did you do it by deleting everything and
following the install procedure from scratch?

**Comment by black111** [comment]
I change the sortDbByField ="time",the result is also not change.
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(running(X1),X2),
      close(X1,X0,27,X2).
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(running(X0),X2),
      close(X1,X0,27,X2).
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(walking(X0),X2),
      close(X1,X0,27,X2),
      happensAt(inactive(X1),X2).
terminatedAt(meeting(X0,X1),X2) :- 
      happensAt(inactive(X0),X2),
      happensAt(walking(X1),X2).
I droped the old collection in mongodb and import the new .
I try to import the project to IDEA and debug the code.Then  I print the caviar-train data and the order of the data is correct ,order by time or _id.

**Comment by nkatzz** [comment]
You do create a new jar each time you change the code right? The order
should be by _id, not time.

**Comment by black111** [comment]
yes,I'm sure,I Import the code to IDEA and run the main method ,the result is also not change.Maybe I can change a compute and run the code .

**Comment by nkatzz** [comment]
If you can try it on a different computer or delete everything and try it
from scratch, that would be helpful. Sorry for the fuzz, but I don't know
what the problem is

**Comment by nkatzz** [comment]
I just tried it on a different computer myself, it seems to be ok...

**Comment by black111** [comment]
I will check out mongodb and try again, maybe my own problem...I feel very sorry...

**Comment by nkatzz** [comment]
No problem, thanks for helping to resolve this. Happy new year!

**Comment by black111** [comment]
Thank you very much for your help and wish you a Happy New Year!...

**Comment by black111** [comment]
I am sorry to bother you again. I really don't know what happened to the theory file. Can you send me the logger file?
I also use your theory.lp ,but the test result is as follows:
tps: 882
fps: 1594
fns: 100
precision: 0.3562197
recall: 0.898167
f-score: 0.51012146
training time:0.0
theory size: 0.0
The number of fps is not correct.

**Comment by nkatzz** [comment]
Hi, attached is the logger file from training and the theory.lp file. Also,
these are the contents of the logger file after I run testing:

09:14:36.105 [main] INFO  app.runutils.CMDArgs$ -
Running with options:
--ada-loss-function=default --test=caviar-test --randorder=true
--parallel-clause-eval=false --shuffle-data=false --fps-weight=1
--onlineprune=false --weight-learning=false
--inpath=/home/nkatz/tmp/caviar-bk --target=None --prune-after=100000
--prequential=true --ada-regularization=0.01 --ties=0.05 --spdepth=1
--trainset=1 --repfor=1 --show-stats=false --wjep=false --mailbox-check=1
--with-ec=true --eval-atleast-on=1000 --ada-delta=1.0
--try-more-rules=false --train=None --delta=0.05 --showrefs=false
--mongo-collection=examples --postprune=true --with-inertia=false
--minseen=1000 --evalth=/home/nkatz/dev/OLED/theory.lp --preprune=1.0
--ada-learn-rate=1.0 --fns-weight=10 --compress-new-rules=true --saveto=
--min-pos-covered=0 --tps-weight=1 --prune=0.0 --scorefun=default
--selftrain=false --mln-weight-at-least=0.1 --coresnum=1
--data-limit=2147483647 --holdout=0 --chunksize=1

09:14:38.641 [HoeffdingLearningSystem-akka.actor.default-dispatcher-2]
INFO  oled.single_core.Dispatcher -
tps: 882
fps: 198
fns: 100
precision: 0.81666666
recall: 0.898167
f-score: 0.8554801
training time:0.0
theory size: 0.0

Try this: Open a terminal and type mongo. Then:

> use caviar-test
switched to db caviar-test
> db.examples.count()
20
> use caviar-train
switched to db caviar-train
> db.examples.count()
970

Do you get the same numbers (20, 970)?

**Comment by black111** [comment]
YEs,I get the same numbers....
MongoDB shell version: 2.6.10
connecting to: test
> show dbs
None          (empty)
admin         (empty)
caviar-test   0.078GB
caviar-train  0.078GB
local         0.078GB
> use caviar-train
switched to db caviar-train
> db.examples.count()
970
> use caviar-test
switched to db caviar-test
> db.examples.count()
20
>

**Comment by nkatzz** [comment]
And when you run the theory.lp file I sent you on caviar-test you get this:

tps: 882
fps: 1594
fns: 100
precision: 0.3562197
recall: 0.898167
f-score: 0.51012146

??

**Comment by black111** [comment]
yes,the result now is changed .fps is 1350...It's so strange.
tps: 882
fps: 1350
fns: 100
precision: 0.3951613
recall: 0.898167
f-score: 0.5488488
training time:0.0
theory size: 0.0

**Comment by nkatzz** [comment]
ok. Let's try something different. Export your caviar-train and caviar-test
dbs and send them to me to see what results I get with them

mongoexport --db caviar-train --collection examples --out caviar-train.json
mongoexport --db caviar-test --collection examples --out caviar-test.json

Send me caviar-train.json and caviar-test.json

**Comment by black111** [comment]
I don't think it's a problem with the dataset. The dataset is almost the same as the online download.I send it to your email.

**Comment by nkatzz** [comment]
Unfortunately, I don't know what to say. The json dumps you sent me are ok.
I imported them into mongo, run everything and get the same results as
previously. I also had two people try the process from scratch on their
computers, they get the same results as I do.

**Comment by nkatzz** [comment]
Can you please send me the exact commands you run from train and for test?

**Comment by black111** [comment]
Yes,the history commands are as folloiws .
Firstly,I download the source code using "git clone". 
1587  git clone https://github.com/nkatzz/OLED.git
 1588  ls
 1589  cd OLED/

Then,run the install.sh and get the datasets.
 1590  cd install-scripts/
 1591  ./install.sh 
 1592  cd ..
 1593  l
 1594  wget http://users.iit.demokritos.gr/~nkatz/oled/caviar-data.zip
 1595  wget http://users.iit.demokritos.gr/~nkatz/oled/caviar-bk.zip
 1596  unzip caviar-data.zip 
 1597  unzip caviar-bk.zip 
 1598  cd caviar-data/
 1599  mongoimport --db caviar-train.json --collection examples --file caviar-train.json 
 1600  mongoimport --db caviar-test.json --collection examples --file caviar-test.json 
 1601  mongo
 1602  cd ..
 1603  java -cp oled-0.1.jar app.runners.OLEDDefaultRunner --inpath=./caviar-bk/ --delta=0.00001 --prune=0.8 --train=caviar-train --saveto=./theory.lp

Tomorrow I will try the process from scratch on someone else's computer and tell you the result. There have been some delays in these days.

**Comment by nkatzz** [comment]
ok. I simplified the demo to avoid confusion. You can use the same command
both for training and for testing:


   - java -cp oled-0.1.jar app.runners.OLEDDefaultRunner --inpath=<PATH TO
   THE caviar-bk FOLDER> --delta=0.00001 --prune=0.8* --train=caviar-train
   --test=caviar-test* --saveto=<PATH TO SOME LOCATION>/theory.lp

You should see the final theory and the evaluation statistics from the test
set printed on screen after learning terminates.

**Comment by black111** [comment]
Something went wrong when I built the project on another computer。
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.github.anskarl#lomrf_2.11;0.5.5-SNAPSHOT: not found
.......
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.github.anskarl#lomrf_2.11;0.5.5-SNAPSHOT: not found
[error] Total time: 40 s, completed Jan 7, 2019 12:21:06 PM
mv: cannot stat 'target/scala-2.11/oled-0.1.jar': No such file or directory

It seems that a dependency cannot be found.

**Comment by black111** [comment]
Something went wrong when I built the project on another computer，It seems that a dependency cannot be found.

[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.github.anskarl#lomrf_2.11;0.5.5-SNAPSHOT: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2550)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: com.github.anskarl#lomrf_2.11;0.5.5-SNAPSHOT: not found
[error] Total time: 6 s, completed Jan 7, 2019 12:46:29 PM
mv: cannot stat 'target/scala-2.11/oled-0.1.jar': No such file or directory

The  command "sbt assembly" failed to run 
My scala version is 2.11.12
